// Banque TOEIC : grammaire (Part 5), lecture (Part 7), listening (Part 2, synthèse vocale).

const TOEIC_GRAMMAR = [
  { text: "The meeting has been postponed ___ next Monday.",
    choices: ["until", "by", "on", "at"], answer: 0,
    expl: "« Postponed until » = reporté jusqu'à. « By » indiquerait une échéance limite, pas un report." },
  { text: "All employees must submit their expense reports ___ Friday at the latest.",
    choices: ["by", "until", "in", "since"], answer: 0,
    expl: "« By + date » = au plus tard le. « Until » = jusqu'à (action continue), incorrect ici." },
  { text: "Ms. Chen is responsible ___ the new marketing campaign.",
    choices: ["of", "for", "to", "with"], answer: 1,
    expl: "« Responsible for something » — préposition figée à mémoriser (≠ français « responsable de »)." },
  { text: "The new software is much ___ than the previous version.",
    choices: ["efficient", "more efficient", "most efficient", "efficiently"], answer: 1,
    expl: "Comparatif avec « than » : « more efficient than ». « Most » = superlatif ; « efficiently » = adverbe." },
  { text: "___ the heavy rain, the outdoor event was a great success.",
    choices: ["Although", "Despite", "However", "Because of"], answer: 1,
    expl: "« Despite + nom ». « Although » exigerait une proposition (sujet + verbe) ; « however » relie deux phrases." },
  { text: "Neither the manager ___ her assistant was available for comment.",
    choices: ["or", "and", "nor", "but"], answer: 2,
    expl: "Corrélatif figé « neither... nor » (ni... ni)." },
  { text: "The contract must be signed ___ both parties before June 30.",
    choices: ["by", "from", "with", "at"], answer: 0,
    expl: "Voix passive : le complément d'agent s'introduit par « by » (signé PAR les deux parties)." },
  { text: "We look forward to ___ from you soon.",
    choices: ["hear", "hearing", "heard", "be heard"], answer: 1,
    expl: "« Look forward to » + gérondif (-ing) : ici « to » est une préposition, pas la marque de l'infinitif. Très fréquent au TOEIC." },
  { text: "The company has ___ its sales targets for three consecutive years.",
    choices: ["exceed", "exceeds", "exceeded", "exceeding"], answer: 2,
    expl: "Present perfect : « has + participe passé » → « has exceeded »." },
  { text: "All new employees ___ to attend the orientation session.",
    choices: ["require", "requiring", "are required", "requirement"], answer: 2,
    expl: "Passif : les employés SONT tenus d'assister → « are required to attend »." },
  { text: "The annual report was ___ detailed and informative.",
    choices: ["both", "either", "neither", "not only"], answer: 0,
    expl: "« Both... and » : ici « both detailed and informative ». « Not only » exigerait « but also »." },
  { text: "___ you have any questions, please do not hesitate to contact the HR department.",
    choices: ["Should", "Would", "Unless", "Whether"], answer: 0,
    expl: "« Should you have... » = inversion formelle équivalant à « If you have... ». Tournure très courante dans les courriels TOEIC." },
  { text: "Prices are subject ___ change without prior notice.",
    choices: ["of", "to", "for", "with"], answer: 1,
    expl: "Expression figée « subject to change » = susceptible d'être modifié." },
  { text: "Mr. Lopez has worked at the Chicago branch ___ 2015.",
    choices: ["for", "since", "during", "from"], answer: 1,
    expl: "« Since + point de départ » (2015) ; « for + durée » (for nine years)." },
  { text: "Your order will be delivered ___ five business days.",
    choices: ["within", "until", "by the time", "at"], answer: 0,
    expl: "« Within + durée » = dans un délai de. « Until » marquerait une continuité jusqu'à un moment donné." },
  { text: "Please review the ___ document before tomorrow's meeting.",
    choices: ["attach", "attached", "attaching", "attachment"], answer: 1,
    expl: "Participe passé adjectival : « the attached document » = le document ci-joint. « Attachment » est le nom (une pièce jointe)." },
  { text: "Sales of the new model increased ___ 15% during the last quarter.",
    choices: ["by", "at", "of", "on"], answer: 0,
    expl: "« Increase by + pourcentage » = augmenter DE 15 %. « Increase to » = atteindre (une valeur)." },
  { text: "___ of the applicants had the required five years of experience.",
    choices: ["Few", "Little", "Much", "Any"], answer: 0,
    expl: "« Applicants » est dénombrable → « few ». « Little » s'emploie avec les indénombrables (little time)." },
  { text: "The CEO announced that the merger ___ completed by the end of June.",
    choices: ["will be", "would be", "has been", "is"], answer: 1,
    expl: "Concordance des temps au discours indirect : « announced that... would be » (futur dans le passé)." },
  { text: "Our team worked ___ to meet the tight deadline.",
    choices: ["efficient", "efficiency", "efficiently", "more efficient"], answer: 2,
    expl: "Il faut un adverbe pour modifier le verbe « worked » → « efficiently »." },
  { text: "The seminar will begin ___ 9:30 sharp.",
    choices: ["at", "in", "on", "by"], answer: 0,
    expl: "« At + heure précise » (at 9:30). « On » + jour, « in » + mois/année." },
  { text: "Employees are encouraged ___ the online training by Friday.",
    choices: ["complete", "completing", "to complete", "completed"], answer: 2,
    expl: "« Encourage somebody TO DO something » : infinitif complet après le passif « are encouraged »." },
  { text: "___ the report is finished, please send it to the director.",
    choices: ["As soon as", "During", "Until", "Despite"], answer: 0,
    expl: "« As soon as » + proposition = dès que. « During » et « despite » exigent un nom." },
  { text: "The new printer is ___ faster than the old model.",
    choices: ["considerable", "considerably", "consideration", "considered"], answer: 1,
    expl: "Adverbe pour intensifier un comparatif : « considerably faster » (nettement plus rapide)." },
  { text: "Ms. Park will be out of the office ___ the end of the week.",
    choices: ["until", "by", "since", "at"], answer: 0,
    expl: "« Until » = jusqu'à (état qui dure). « By » = au plus tard (échéance ponctuelle)." },
  { text: "Please make sure that all windows ___ before leaving.",
    choices: ["are locked", "lock", "locking", "to lock"], answer: 0,
    expl: "Sens passif : les fenêtres SONT verrouillées → « are locked »." },
  { text: "The two companies signed a five-year ___ last week.",
    choices: ["agree", "agreement", "agreeable", "agreeably"], answer: 1,
    expl: "Après un article + adjectif, il faut un nom : « an agreement ». Famille de mots — question très fréquente." },
  { text: "___ employees who park in the garage must register their vehicle.",
    choices: ["All", "Every", "Each of", "Much"], answer: 0,
    expl: "« All + pluriel ». « Every » et « each » se construisent avec un singulier ; « each of » exigerait « the »." },
  { text: "The keynote speaker arrived late ___ the heavy traffic.",
    choices: ["because", "due to", "although", "so that"], answer: 1,
    expl: "« Due to + nom » = en raison de. « Because » exigerait une proposition (because the traffic was heavy)." },
  { text: "Mr. Alvarez asked his assistant to book a flight for ___.",
    choices: ["he", "his", "him", "himself"], answer: 2,
    expl: "Pronom complément après « for » : « him » (= M. Alvarez). « Himself » renverrait au sujet de « book », c'est-à-dire l'assistant." },
  { text: "Our sales have grown ___ since the new campaign started.",
    choices: ["steady", "steadier", "steadily", "steadiness"], answer: 2,
    expl: "Adverbe pour modifier « have grown » : « steadily » (régulièrement)." },
  { text: "The warranty is valid for two years from the date of ___.",
    choices: ["purchase", "purchased", "purchasing them", "purchaser"], answer: 0,
    expl: "« Date of purchase » = date d'achat (nom). « Purchaser » = l'acheteur (personne)." },
  { text: "___ candidates should submit two letters of reference.",
    choices: ["Interest", "Interested", "Interesting", "Interestingly"], answer: 1,
    expl: "« Interested candidates » = les candidats intéressés (participe passé). « Interesting » = qui suscite l'intérêt." },
  { text: "The manager insisted that the report ___ submitted by noon.",
    choices: ["is", "be", "was", "has been"], answer: 1,
    expl: "Subjonctif après « insist/require/recommend that » : base verbale « be ». Tournure formelle typique du TOEIC." },
  { text: "You can reach our customer service ___ phone or email.",
    choices: ["by", "on", "in", "with"], answer: 0,
    expl: "« By phone / by email » = moyen de communication." },
  { text: "The elevator will be out of service ___ further notice.",
    choices: ["for", "until", "by", "within"], answer: 1,
    expl: "Expression figée « until further notice » = jusqu'à nouvel ordre." },
  { text: "___ of the two proposals was accepted by the committee.",
    choices: ["Neither", "None", "Not", "No"], answer: 0,
    expl: "Pour deux éléments : « neither » (aucun des deux). « None » s'emploie à partir de trois." },
  { text: "The training session has been moved ___ Room 204.",
    choices: ["to", "at", "on", "in"], answer: 0,
    expl: "« Move to + lieu » : déplacement vers. « In/at » indiqueraient une position statique." },
  { text: "Ms. Chen speaks ___ of the three sales representatives.",
    choices: ["most persuasively", "more persuasively", "persuasively", "persuasive"], answer: 0,
    expl: "Superlatif (trois personnes) avec adverbe : « (the) most persuasively ». « More » ne compare que deux éléments." },
  { text: "Visitors must wear their badges ___ while on company premises.",
    choices: ["at all times", "sometime", "overtime", "on time"], answer: 0,
    expl: "« At all times » = en permanence. « On time » = à l'heure ; « overtime » = heures supplémentaires." },
  { text: "The merger is expected to result ___ significant cost savings.",
    choices: ["in", "of", "at", "from"], answer: 0,
    expl: "« Result in » = aboutir à (conséquence). « Result from » = découler de (cause)." },
  { text: "___ signing the contract, please read the terms and conditions carefully.",
    choices: ["Before", "Yet", "Until", "Once again that"], answer: 0,
    expl: "« Before + -ing » = avant de. Construction prépositionnelle classique." },
  { text: "The hotel offers a complimentary shuttle service ___ its guests.",
    choices: ["for", "at", "on", "about"], answer: 0,
    expl: "Un service « for guests » = destiné aux clients. « Complimentary » = gratuit (vocabulaire TOEIC fréquent)." },
  { text: "Ms. Ito was promoted ___ regional manager last month.",
    choices: ["to", "for", "in", "by"], answer: 0,
    expl: "« Promote somebody TO + poste » : elle a été promue AU poste de directrice régionale." },
  { text: "The device comes with ___ instructions in five languages.",
    choices: ["detail", "details", "detailed", "detailing"], answer: 2,
    expl: "Adjectif devant le nom : « detailed instructions » = des instructions détaillées." },
  { text: "___ the new intern nor the assistant knows the door code.",
    choices: ["Either", "Neither", "Both", "Not only"], answer: 1,
    expl: "Corrélatif « neither… nor ». « Either » irait avec « or », « both » avec « and », « not only » avec « but also »." },
  { text: "Quarterly results will be discussed ___ the next board meeting.",
    choices: ["at", "on", "to", "from"], answer: 0,
    expl: "« At a meeting » = lors d'une réunion (événement)." },
  { text: "The conference room was ___ small to hold all the attendees.",
    choices: ["too", "so", "very", "enough"], answer: 0,
    expl: "Structure « too + adjectif + to » = trop… pour. « Enough » se placerait après l'adjectif (small enough)." },
  { text: "We apologize for ___ inconvenience this delay may cause.",
    choices: ["any", "some", "every", "few"], answer: 0,
    expl: "Formule consacrée : « we apologize for any inconvenience » — « any » convient aux contextes d'éventualité." },
  { text: "The figures in this report are not ___ with last year's data.",
    choices: ["consist", "consistent", "consistency", "consistently"], answer: 1,
    expl: "Après « are not », il faut un adjectif : « consistent with » = cohérent avec." },
  { text: "Applications received after the deadline ___ be considered.",
    choices: ["will not", "do not", "are not", "have not"], answer: 0,
    expl: "Futur : les candidatures tardives NE SERONT PAS étudiées → « will not be considered »." },
  { text: "The award ceremony will be moved indoors ___ of rain.",
    choices: ["in case", "in front", "because", "instead"], answer: 0,
    expl: "« In case of + nom » = en cas de. « Because » exigerait « because of »." },
  { text: "Mr. Diaz is ___ for approving all travel expenses.",
    choices: ["responsible", "response", "responsive", "responsibly"], answer: 0,
    expl: "« Responsible for » = chargé de. « Responsive » = réactif — piège de famille de mots." },
  { text: "Orders placed before noon are ___ shipped the same day.",
    choices: ["usual", "usually", "usualness", "as usual"], answer: 1,
    expl: "Adverbe de fréquence modifiant le verbe passif : « are usually shipped »." },
  { text: "___ who wish to attend the workshop must RSVP by Friday.",
    choices: ["Those", "These", "They", "Them"], answer: 0,
    expl: "« Those who » = ceux qui (antécédent indéfini). Tournure très fréquente au TOEIC." },
  { text: "The intern completed the entire project ___ any assistance.",
    choices: ["without", "unless", "except", "besides"], answer: 0,
    expl: "« Without any assistance » = sans aucune aide." },
  { text: "Prices have remained ___ despite rising production costs.",
    choices: ["stable", "stably", "stability", "stabilize"], answer: 0,
    expl: "« Remain » est un verbe d'état suivi d'un adjectif attribut : « remain stable »." },
  { text: "The airline is not liable ___ delays caused by severe weather.",
    choices: ["for", "of", "to", "about"], answer: 0,
    expl: "« Liable for » = responsable de (dommages, retards). Préposition figée." },
  { text: "Please ___ your seat belt whenever the sign is on.",
    choices: ["fasten", "fastened", "fastening", "fastens"], answer: 0,
    expl: "Impératif : base verbale « fasten ». Vocabulaire transport très courant au TOEIC." },
  { text: "The audit highlighted several areas ___ improvement.",
    choices: ["for", "of", "at", "by"], answer: 0,
    expl: "« Areas for improvement » = axes d'amélioration (expression consacrée des contextes professionnels)." }
];

const TOEIC_READING = [
  {
    title: "E-mail — Office relocation",
    passage: `From: facilities@nordicatech.com
To: All staff
Subject: Office relocation — action required
Date: March 3

Dear colleagues,

As announced at last month's all-hands meeting, our office will move to the Riverside Business Park on Friday, March 21. The new building offers twice as much meeting space, a staff cafeteria, and direct access to the Line 4 subway station.

To prepare for the move, please pack your personal belongings in the boxes that will be distributed on March 17, and clearly label each box with your name and your new floor number, which you can find on the intranet. IT equipment should NOT be packed: the technical team will handle all computers and monitors on the evening of March 20.

The office will be closed on Friday, March 21. All employees are expected to work remotely that day. Normal operations will resume at the new location on Monday, March 24.

Questions? Contact the facilities team before March 14.

Best regards,
Facilities Department`,
    questions: [
      { text: "What is the main purpose of the e-mail?",
        choices: [
          "To announce the construction of a cafeteria",
          "To give employees instructions about an office move",
          "To invite staff to an all-hands meeting",
          "To report a problem with IT equipment"
        ],
        answer: 1,
        expl: "L'objet (« action required ») et le corps du message donnent les consignes du déménagement. Les autres éléments (cafétéria, réunion) ne sont que des détails." },
      { text: "What are employees asked to do with their computers?",
        choices: [
          "Pack them in labeled boxes",
          "Take them home on March 20",
          "Leave them for the technical team to handle",
          "Return them to the facilities department"
        ],
        answer: 2,
        expl: "« IT equipment should NOT be packed: the technical team will handle all computers... » — piège classique sur la négation." },
      { text: "What will happen on March 21?",
        choices: [
          "Employees will work from the new office.",
          "Boxes will be distributed to the staff.",
          "The office will be closed and staff will work remotely.",
          "An all-hands meeting will take place."
        ],
        answer: 2,
        expl: "« The office will be closed on Friday, March 21. All employees are expected to work remotely that day. »" },
      { text: "What is suggested about the new building?",
        choices: [
          "It is smaller than the current office.",
          "It is conveniently located near public transportation.",
          "It has no meeting rooms yet.",
          "It will open in June."
        ],
        answer: 1,
        expl: "« Direct access to the Line 4 subway station » → bien desservi par les transports. Inférence typique de la Part 7." }
    ]
  },
  {
    title: "Notice — Extended warranty offer",
    passage: `GREENFIELD APPLIANCES — CUSTOMER NOTICE

Thank you for purchasing a Greenfield appliance. Your product is covered by our standard two-year warranty, which includes parts and labor for any manufacturing defect.

For a limited time, customers who register their product online before April 30 will receive an additional year of coverage at no extra cost. To register, visit www.greenfield.com/register and enter the serial number printed on the back of your appliance, along with your proof of purchase.

Please note that the warranty does not cover damage caused by improper installation, power surges, or use of non-approved accessories. Repairs performed by unauthorized technicians will void the warranty.

For service requests, call our customer hotline at 1-800-555-0142, Monday through Saturday, 8 A.M. to 6 P.M.`,
    questions: [
      { text: "What is offered to customers who register before April 30?",
        choices: [
          "A discount on their next purchase",
          "A free accessory",
          "One extra year of warranty coverage",
          "Free installation of the appliance"
        ],
        answer: 2,
        expl: "« Will receive an additional year of coverage at no extra cost. »" },
      { text: "What do customers need in order to register their product?",
        choices: [
          "A credit card number",
          "The serial number and a proof of purchase",
          "The technician's authorization code",
          "A copy of the standard warranty"
        ],
        answer: 1,
        expl: "« Enter the serial number... along with your proof of purchase. »" },
      { text: "According to the notice, what would void the warranty?",
        choices: [
          "Registering the product online",
          "Calling the customer hotline",
          "Using the appliance every day",
          "Having the appliance repaired by an unauthorized technician"
        ],
        answer: 3,
        expl: "« Repairs performed by unauthorized technicians will void the warranty. » « To void » = annuler, rendre nul." },
      { text: "When can customers call the service hotline?",
        choices: [
          "Every day of the week",
          "Monday through Saturday, from 8 A.M. to 6 P.M.",
          "Only before April 30",
          "Weekdays after 6 P.M."
        ],
        answer: 1,
        expl: "Dernière phrase : « Monday through Saturday, 8 A.M. to 6 P.M. » — le dimanche est exclu." }
    ]
  }
];

// Part 2 : une question lue à voix haute, trois réponses lues à voix haute.
// L'utilisateur choisit A, B ou C sans voir les textes (comme au vrai TOEIC).
const TOEIC_LISTENING = [
  { q: "When does the next train to Boston leave?",
    r: ["At four thirty.", "By train, usually.", "Two tickets, please."], answer: 0,
    expl: "Question en « When » → on attend un horaire. B répond à « how », C répond à une question d'achat." },
  { q: "Where is the accounting department?",
    r: ["Yes, it is.", "On the third floor.", "Every Monday morning."], answer: 1,
    expl: "Question en « Where » → un lieu. « Yes/No » ne répond jamais à une question en WH- : piège récurrent." },
  { q: "Who is leading the meeting today?",
    r: ["In the conference room.", "At ten o'clock.", "Ms. Tanaka is."], answer: 2,
    expl: "Question en « Who » → une personne. A donne un lieu, B un horaire." },
  { q: "Would you like some coffee before we start?",
    r: ["Yes, please.", "In the kitchen.", "No, he doesn't."], answer: 0,
    expl: "Offre polie → acceptation ou refus poli. C utilise « he », incohérent avec « you »." },
  { q: "How long is the flight to Chicago?",
    r: ["By plane.", "About two hours.", "Seat twelve A."], answer: 1,
    expl: "« How long » → une durée. A répond à « how » (moyen), C évoque un siège." },
  { q: "Why was this morning's meeting cancelled?",
    r: ["Because the director is away on business.", "In the meeting room.", "Yes, it was."], answer: 0,
    expl: "« Why » → une cause (« because... »). « Yes/No » est impossible après une question en WH-." },
  { q: "Could you send me the sales report by Friday?",
    r: ["The airport is quite far.", "Sure, no problem.", "Twice a week."], answer: 1,
    expl: "Demande polie → accepter ou refuser. Piège phonétique : « report » / « airport »." },
  { q: "Whose laptop is this on the table?",
    r: ["It's brand new.", "On the desk.", "It's Maria's."], answer: 2,
    expl: "« Whose » → un possesseur (génitif « Maria's »). A décrit l'objet, B donne un lieu." },
  { q: "Have you finished the presentation yet?",
    r: ["Almost — I'll be done by noon.", "Yes, tomorrow.", "It was a gift."], answer: 0,
    expl: "« Yes, tomorrow » est contradictoire (fini... demain ?). « Present/presentation » : piège phonétique en C." },
  { q: "Should we take a taxi or the subway?",
    r: ["Yes, we should.", "At the station.", "The subway is faster."], answer: 2,
    expl: "Question alternative (« or ») → on choisit l'une des options. « Yes/No » est le piège classique des questions en « or »." },
  { q: "What time does the pharmacy close tonight?",
    r: ["At nine P.M.", "Near the bank.", "Some medicine, please."], answer: 0,
    expl: "« What time » → un horaire. B répond à « where », C répond à « what would you like »." },
  { q: "You've met our new client before, haven't you?",
    r: ["No, it's not mine.", "Yes, at the conference last week.", "A new contract."], answer: 1,
    expl: "Question tag → confirmation/infirmation cohérente. A répond à une question de possession." }
];
