// Vocabulaire TOEIC — 80 mots/expressions business essentiels.
// Utilisé par le module de flashcards à répétition espacée.

const TOEIC_VOCAB = [
  { w: "attend", pos: "v.", fr: "assister à, participer à", ex: "All managers must attend the meeting." },
  { w: "schedule", pos: "n./v.", fr: "programme, horaire / planifier", ex: "The meeting is scheduled for Monday." },
  { w: "deadline", pos: "n.", fr: "date limite, échéance", ex: "The deadline for applications is Friday." },
  { w: "invoice", pos: "n.", fr: "facture", ex: "Please pay the invoice within 30 days." },
  { w: "supplier", pos: "n.", fr: "fournisseur", ex: "We found a cheaper supplier for office paper." },
  { w: "hire", pos: "v.", fr: "embaucher", ex: "The company plans to hire ten engineers." },
  { w: "apply for", pos: "v.", fr: "postuler à", ex: "She applied for the marketing position." },
  { w: "applicant", pos: "n.", fr: "candidat", ex: "Over fifty applicants sent their résumés." },
  { w: "résumé", pos: "n.", fr: "CV (anglais américain)", ex: "Please attach your résumé to the e-mail." },
  { w: "appointment", pos: "n.", fr: "rendez-vous", ex: "I have an appointment with the dentist at 3." },
  { w: "branch", pos: "n.", fr: "succursale, agence", ex: "Our Tokyo branch opened last year." },
  { w: "headquarters", pos: "n.", fr: "siège social", ex: "The headquarters are located in Berlin." },
  { w: "warehouse", pos: "n.", fr: "entrepôt", ex: "The goods are stored in the warehouse." },
  { w: "shipment", pos: "n.", fr: "expédition, cargaison", ex: "The shipment will arrive next week." },
  { w: "delay", pos: "n./v.", fr: "retard / retarder", ex: "The flight was delayed by two hours." },
  { w: "refund", pos: "n./v.", fr: "remboursement / rembourser", ex: "You can get a full refund within 14 days." },
  { w: "receipt", pos: "n.", fr: "reçu, ticket de caisse", ex: "Keep your receipt as proof of purchase." },
  { w: "purchase", pos: "n./v.", fr: "achat / acheter", ex: "The receipt confirms your purchase." },
  { w: "order", pos: "n./v.", fr: "commande / commander", ex: "Your order has been shipped." },
  { w: "estimate", pos: "n./v.", fr: "devis, estimation / estimer", ex: "The plumber gave us an estimate of $400." },
  { w: "agenda", pos: "n.", fr: "ordre du jour", ex: "The budget is the first item on the agenda." },
  { w: "minutes", pos: "n.", fr: "compte rendu (de réunion)", ex: "She took the minutes of the meeting." },
  { w: "draft", pos: "n./v.", fr: "brouillon / rédiger", ex: "Please review the first draft of the report." },
  { w: "review", pos: "v./n.", fr: "examiner, relire / examen", ex: "The board will review the proposal." },
  { w: "approve", pos: "v.", fr: "approuver", ex: "The budget was approved by the board." },
  { w: "budget", pos: "n.", fr: "budget", ex: "The project is over budget." },
  { w: "forecast", pos: "n./v.", fr: "prévision / prévoir", ex: "The sales forecast looks promising." },
  { w: "revenue", pos: "n.", fr: "chiffre d'affaires, recettes", ex: "Revenue grew by 12% this year." },
  { w: "expense", pos: "n.", fr: "dépense, frais", ex: "Travel expenses are reimbursed." },
  { w: "profit", pos: "n.", fr: "bénéfice", ex: "The company made a record profit." },
  { w: "loss", pos: "n.", fr: "perte", ex: "The division reported a loss last quarter." },
  { w: "shareholder", pos: "n.", fr: "actionnaire", ex: "Shareholders will vote at the annual meeting." },
  { w: "board", pos: "n.", fr: "conseil d'administration", ex: "The board meets every quarter." },
  { w: "merger", pos: "n.", fr: "fusion (d'entreprises)", ex: "The merger created the largest bank in Asia." },
  { w: "acquire", pos: "v.", fr: "acquérir, racheter", ex: "The firm acquired a smaller competitor." },
  { w: "subsidiary", pos: "n.", fr: "filiale", ex: "The group owns several subsidiaries abroad." },
  { w: "retail", pos: "n./adj.", fr: "vente au détail", ex: "Retail prices include tax." },
  { w: "wholesale", pos: "n./adj.", fr: "vente en gros", ex: "We buy wholesale and sell retail." },
  { w: "customer", pos: "n.", fr: "client (d'un commerce)", ex: "Customer satisfaction is our priority." },
  { w: "complaint", pos: "n.", fr: "plainte, réclamation", ex: "We received a complaint about the service." },
  { w: "warranty", pos: "n.", fr: "garantie", ex: "The laptop comes with a two-year warranty." },
  { w: "feature", pos: "n.", fr: "caractéristique, fonctionnalité", ex: "The new phone has several innovative features." },
  { w: "launch", pos: "v./n.", fr: "lancer / lancement", ex: "The product will be launched in May." },
  { w: "advertise", pos: "v.", fr: "faire de la publicité", ex: "They advertise on social media." },
  { w: "survey", pos: "n./v.", fr: "enquête, sondage / sonder", ex: "The survey shows customers want faster delivery." },
  { w: "target", pos: "n./v.", fr: "objectif, cible / viser", ex: "We reached our sales target." },
  { w: "achieve", pos: "v.", fr: "atteindre, réaliser", ex: "She achieved all her goals this year." },
  { w: "exceed", pos: "v.", fr: "dépasser", ex: "Results exceeded expectations." },
  { w: "improve", pos: "v.", fr: "améliorer", ex: "We must improve our response time." },
  { w: "increase", pos: "v./n.", fr: "augmenter / hausse", ex: "Prices increased by 5%." },
  { w: "decrease", pos: "v./n.", fr: "diminuer / baisse", ex: "Costs decreased significantly." },
  { w: "available", pos: "adj.", fr: "disponible", ex: "The manager is not available right now." },
  { w: "currently", pos: "adv.", fr: "actuellement", ex: "We are currently hiring. (≠ « couramment »)" },
  { w: "approximately", pos: "adv.", fr: "environ", ex: "The trip takes approximately two hours." },
  { w: "immediately", pos: "adv.", fr: "immédiatement", ex: "Please reply immediately." },
  { w: "frequently", pos: "adv.", fr: "fréquemment", ex: "Trains run frequently during rush hour." },
  { w: "however", pos: "adv.", fr: "cependant", ex: "The offer is attractive; however, it is risky." },
  { w: "therefore", pos: "adv.", fr: "par conséquent", ex: "It rained; therefore, the event was moved indoors." },
  { w: "although", pos: "conj.", fr: "bien que", ex: "Although it was late, she kept working." },
  { w: "despite", pos: "prep.", fr: "malgré (+ nom)", ex: "Despite the rain, the event was a success." },
  { w: "due to", pos: "prep.", fr: "en raison de", ex: "The flight was cancelled due to fog." },
  { w: "in charge of", pos: "exp.", fr: "responsable de", ex: "She is in charge of recruitment." },
  { w: "look forward to", pos: "exp.", fr: "attendre avec impatience (+ -ing)", ex: "I look forward to hearing from you." },
  { w: "carry out", pos: "v.", fr: "effectuer, mener à bien", ex: "We carried out a customer survey." },
  { w: "set up", pos: "v.", fr: "créer, installer, organiser", ex: "They set up a meeting for Tuesday." },
  { w: "fill out", pos: "v.", fr: "remplir (un formulaire)", ex: "Please fill out this application form." },
  { w: "find out", pos: "v.", fr: "découvrir, apprendre", ex: "I'll find out when the train leaves." },
  { w: "run out of", pos: "v.", fr: "être à court de", ex: "We've run out of printer paper." },
  { w: "put off", pos: "v.", fr: "reporter, remettre à plus tard", ex: "The meeting was put off until next week." },
  { w: "call off", pos: "v.", fr: "annuler", ex: "The event was called off because of the storm." },
  { w: "figure out", pos: "v.", fr: "comprendre, résoudre", ex: "We need to figure out what went wrong." },
  { w: "take over", pos: "v.", fr: "reprendre, racheter (une entreprise)", ex: "A rival firm took over the company." },
  { w: "turn down", pos: "v.", fr: "refuser, rejeter", ex: "She turned down the job offer." },
  { w: "comply with", pos: "v.", fr: "se conformer à", ex: "All factories must comply with safety rules." },
  { w: "in advance", pos: "exp.", fr: "à l'avance", ex: "Please book your tickets in advance." },
  { w: "on behalf of", pos: "exp.", fr: "au nom de, de la part de", ex: "I'm calling on behalf of Mr. Davis." },
  { w: "out of stock", pos: "exp.", fr: "en rupture de stock", ex: "This item is currently out of stock." },
  { w: "under construction", pos: "exp.", fr: "en travaux", ex: "The new wing is still under construction." },
  { w: "subject to", pos: "exp.", fr: "soumis à, susceptible de", ex: "Prices are subject to change." },
  { w: "free of charge", pos: "exp.", fr: "gratuit", ex: "Delivery is free of charge over $50." },
  { w: "reimburse", pos: "v.", fr: "rembourser (des frais)", ex: "The company will reimburse your travel expenses." },
  { w: "postpone", pos: "v.", fr: "reporter", ex: "The launch was postponed until next month." },
  { w: "attend to", pos: "v.", fr: "s'occuper de", ex: "A staff member will attend to your request." },
  { w: "in charge", pos: "exp.", fr: "responsable, aux commandes", ex: "Who is in charge here?" },
  { w: "shift", pos: "n.", fr: "poste, tranche horaire", ex: "She works the night shift." },
  { w: "overtime", pos: "n.", fr: "heures supplémentaires", ex: "He was paid for two hours of overtime." },
  { w: "raise", pos: "n.", fr: "augmentation de salaire", ex: "She asked her boss for a raise." },
  { w: "resign", pos: "v.", fr: "démissionner", ex: "He resigned from his position last week." },
  { w: "promotion", pos: "n.", fr: "promotion (poste)", ex: "She earned a promotion to manager." },
  { w: "candidate", pos: "n.", fr: "candidat", ex: "We interviewed five candidates." },
  { w: "vacancy", pos: "n.", fr: "poste vacant", ex: "There is a vacancy in the sales team." },
  { w: "internship", pos: "n.", fr: "stage", ex: "She did a summer internship at a law firm." },
  { w: "colleague", pos: "n.", fr: "collègue", ex: "My colleagues are very supportive." },
  { w: "commute", pos: "n./v.", fr: "trajet domicile-travail / faire la navette", ex: "My commute takes an hour each way." },
  { w: "premises", pos: "n.", fr: "locaux", ex: "Smoking is not allowed on the premises." },
  { w: "facility", pos: "n.", fr: "installation, équipement", ex: "The hotel has excellent conference facilities." },
  { w: "maintenance", pos: "n.", fr: "entretien", ex: "The elevator is closed for maintenance." },
  { w: "renovation", pos: "n.", fr: "rénovation", ex: "The lobby is under renovation." },
  { w: "inventory", pos: "n.", fr: "stock, inventaire", ex: "We take inventory at the end of each month." },
  { w: "quote", pos: "n./v.", fr: "devis / établir un devis", ex: "They sent us a quote for the repairs." },
  { w: "deposit", pos: "n.", fr: "acompte, dépôt", ex: "A 20% deposit is required to confirm the booking." },
  { w: "installment", pos: "n.", fr: "versement échelonné", ex: "You can pay in three monthly installments." },
  { w: "outstanding", pos: "adj.", fr: "impayé, en souffrance / remarquable", ex: "The outstanding balance must be paid by Friday." },
  { w: "on schedule", pos: "exp.", fr: "dans les temps", ex: "The project is on schedule." },
  { w: "behind schedule", pos: "exp.", fr: "en retard", ex: "Construction is two weeks behind schedule." },
  { w: "ahead of", pos: "exp.", fr: "en avance sur", ex: "We finished ahead of the deadline." },
  { w: "up to date", pos: "exp.", fr: "à jour", ex: "Please keep your records up to date." },
  { w: "keep track of", pos: "exp.", fr: "suivre, garder trace de", ex: "This app helps you keep track of expenses." },
  { w: "on hand", pos: "exp.", fr: "disponible, en stock", ex: "We don't have that model on hand right now." },
  { w: "in stock", pos: "exp.", fr: "en stock", ex: "The item is back in stock." },
  { w: "sold out", pos: "exp.", fr: "épuisé, complet", ex: "The concert is completely sold out." },
  { w: "attendee", pos: "n.", fr: "participant (à un événement)", ex: "All attendees received a name badge." },
  { w: "venue", pos: "n.", fr: "lieu (d'un événement)", ex: "The conference venue is near the station." },
  { w: "keynote", pos: "n.", fr: "discours d'ouverture", ex: "The CEO gave the keynote speech." },
  { w: "handout", pos: "n.", fr: "document distribué", ex: "Please take a handout as you enter." },
  { w: "reschedule", pos: "v.", fr: "reprogrammer", ex: "We had to reschedule the interview." },
  { w: "prompt", pos: "adj.", fr: "rapide, ponctuel", ex: "Thank you for your prompt reply." }
];
